apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: tax-calculator-pipeline
spec:
  params:
    - name: image-url
      type: string
    - name: repo-url
      type: string
  workspaces:
    - name: source
  tasks:
    - name: clone
      taskRef:
        name: git-clone
        kind: ClusterTask
      params:
        - name: url
          value: $(params.repo-url)
      workspaces:
        - name: output
          workspace: source

    - name: npminstall
      taskRef:
        name: npm
      runAfter:
        - clone
      workspaces:
        - name: source
          workspace: source

    - name: tests
      taskRef:
        name: jasmine
      runAfter:
        - npminstall
      workspaces:
        - name: source
          workspace: source

    - name: build
      taskRef:
        name: buildah
        kind: ClusterTask
      runAfter:
        - tests
      params:
        - name: IMAGE
          value: $(params.image-url)
        - name: DOCKERFILE
          value: ./Dockerfile
      workspaces:
        - name: source
          workspace: source
