apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: tax-calculator-pipeline-run
spec:
  pipelineRef:
    name: tax-calculator-pipeline
  params:
    - name: image-url
      value: us.icr.io/sn-labs-yournamespace/tax-calculator:latest
    - name: repo-url
      value: https://github.com/yourusername/tax-calculator.git
  workspaces:
    - name: source
      persistentVolumeClaim:
        claimName: pipeline-pvc
