apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: npm
spec:
  workspaces:
    - name: source
  steps:
    - name: npm
      image: node:alpine3.17
      workingDir: $(workspaces.source.path)
      command: ["/bin/sh"]
      args:
        - "-c"
        - "npm install && npm fund"

---

apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: jasmine
spec:
  workspaces:
    - name: source
  steps:
    - name: jasmine
      image: node:alpine3.17
      workingDir: $(workspaces.source.path)
      command: ["/bin/sh"]
      args:
        - "-c"
        - "npm install -g jasmine && jasmine"
