apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: npm-install
spec:
  workspaces:
    - name: source
  steps:
    - name: npm-install
      image: node:18-alpine
      workingDir: $(workspaces.source.path)
      command: ["npm"]
      args: ["install"]

---

apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: run-tests-jasmine
spec:
  workspaces:
    - name: source
  steps:
    - name: run-jasmine
      image: node:18-alpine
      workingDir: $(workspaces.source.path)
      command: ["npx"]
      args: ["jasmine"]
